- name: Unarchive worker.tar
  become: true
  register: worker
  unarchive:
    src: ../../../worker.tar
    dest: /opt/

- name: Upload .service
  become: true
  register: service
  template:
    src: ../files/worker.service
    dest: /etc/systemd/system/
    owner: root
    group: root
    mode: '0644'

- name: Install Java
  become: true
  apt:
    state: present
    update_cache: yes
    name: 
      - openjdk-11-jdk
      - maven
      - default-jdk
      - default-jre

- name: Build project with Maven
  command: mvn clean package -f /opt/worker/pom.xml
  register: maven
  args:
    chdir: /opt/worker

- name: Copy good path .jar
  when: maven.changed
  register: copy
  copy: 
    remote_src: True 
    src: "{{ item }}"
    dest: /opt
  loop:
    - /opt/worker/target/worker.jar
    - /opt/worker/target/worker-jar-with-dependencies.jar

- name: Remove unless-files
  when: copy.changed
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /opt/worker/target/worker-jar-with-dependencies.jar
    - /opt/worker/target/worker.jar
    - /opt/worker/target/generated-sources
    - /opt/worker/target/archive-tmp
    - /opt/worker/target/maven-archiver
    - /opt/worker/target/maven-status

- name: Start service
  become: true
  when: service.changed
  systemd:
    name: worker
    state: restarted
    enabled: yes

- name: ufw rules
  become: true
  community.general.ufw:
    rule: "allow"
    port: "{{ item }}"
    proto: "tcp"
  with_items:
    - "80"